weekend 2 assesment
learn-academy-2023-alpha/week-2-assessment-RichDTran pull request #1
Opened 2023-02-27 08:39 UTC by RichDTran

# Submitting Week 2 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Coding Concepts
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-02-28 22:31 UTC, Genemichael25 requested changes
Dennis I am requesting changes for interview questions regarding iteration and differences between a function and a method. Researched answers need to be in your own words, and should expand on your initial answer. We can use resources to understand the concepts, but copy and paste is not acceptable. Please message me when you have made the changes. I have left a few comments throughout for you to take a look at as well. Currently, this assessment is at a complete level.

2023-02-28 22:31 UTC, Genemichael25 commented on code-challenges.test.js
> +//     it("returns a statement with the appropriate coffee order", () => {
The it block should reflect what you want the test to check for. Coffee order for this challenge question doesn't seem appropriate.

2023-02-28 22:31 UTC, Genemichael25 commented on code-challenges.test.js
> +// }
Good job with this function! Make sure you include charAt and how you intend to use it in your pseudocode. You can also talk about how you will slice from index 1 and why that makes sense for this problem.

2023-02-28 22:31 UTC, Genemichael25 commented on code-challenges.test.js
> +
I like that you are attempting different ways. This is an excellent example of where pseudocode will really help you think each step and understand if you are missing something. Things like understanding what .include will produce or if .length will be useful.

2023-02-28 22:31 UTC, Genemichael25 commented on coding-concepts.js
> +
Great job! Keep in mind that the space will also be included in the array

2023-02-28 22:31 UTC, Genemichael25 commented on coding-concepts.js
> +// verifying these numbers are odd and are returned.
Exactly, great job explaining filter in this situation!

2023-02-28 22:31 UTC, Genemichael25 commented on interview-questions.md
> +                    const argument = "LEARN"
We can think of a parameter as a placeholder for when we are given the data to pass into the function, or the argument. Good job including an example!

2023-02-28 22:31 UTC, Genemichael25 commented on interview-questions.md
> +Researched answer: .map is a collections of key value pairs. It does not contain any keys by default. it only contains what is explicitly put into it. It can be any value like functions objecs or any
See what you can find about .map parameters. Key value pairs are found in objects. .map is a HOF

2023-02-28 22:31 UTC, Genemichael25 commented on interview-questions.md
> +                                            for (string) =>{
Researched answers need to be in your own words! We want to know what you understand and not what we can find on the internet and copy/paste.

2023-02-28 22:31 UTC, Genemichael25 commented on interview-questions.md
Same thing here! And if you are going to provide examples, they need to be explained.

2023-03-03 19:08 UTC, nmaresrivera11 approved these changes
Dennis, great job getting through this one! You took the advice and overcame. You have great foundational knowledge and I would like you to build on that! Take some time to read just one of the several different JavaScript methods and get solid on that one, next week another and so on. This assessment comprehension level is a novice but I see you being able to level up within the upcoming assessment. Following the Dreyfus model of skill acquisition here at learn, this is to include pseudo code with proper vocabulary terms, "your answers" written in complete sentences the student's own words that provide partially correct comments, researched answers written in complete sentences in the student's own words that provides additional context, and code that will output correct content in the terminal.

2023-03-03 21:02 UTC, merged